# Generated by Django 4.0.2 on 2022-06-24 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_group_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='user',
        ),
    ]
